### ISSUE TITLE
KeyError raised when a message doesn't have a title.

### ISSUE THREAD

**Issue by gw1urf** [Aeirsoul/py-pushover-open-client#3]
In the __init__ function, you have the following:

`self.title = messageJson["title"]`

If a message doesn't have a title, this generates a KeyError exception

I've fixed it in my copy by changing this line to say:

`self.title = messageJson["title"] if "title" in messageJson else None`

**Comment by jonogreenz** [comment]
Interesting, I believe I thought that all messages are required to have a title, but nonetheless I'll change this now - thanks
