### ISSUE TITLE
Naming of repository

### ISSUE THREAD

**Issue by Joe-houghton** [Aeirsoul/py-pushover-open-client#4]
Hi I am developing using this library, so thanks for that, its working really well.

I am using using your repository as a submodule using the syntax:

`from py-pushover-open-client.pushover_open_client import Client`
However python complains at it has the - symbol in, so I am having to rename the folder locally to
`from py_pushover_open_client.pushover_open_client import Client`

My repository is here if you wanted to take a look to see what I mean.
[IFTTTtoDomoticzUsingPushover](https://github.com/Joe-houghton/IFTTTtoDomoticzUsingPushover)

I know there are other ways around this such as taking the python file (with copyright/license/credit, etc) and putting it in my own repository, however I prefer to link to your repository, so it gives you the credit and also if you make updates (such as the empty title issue, which, I also hit).

Any other suggestions welcome.

Thanks Joe

**Comment by jonogreenz** [comment]
Cheers Joe - I'll look into this further this evening. I was never sure the correct procedure for actually redistributing a python library/binding, but just copied what I'd seen at the time. I'll relook into this and will see if renaming is the best solution!

**Comment by jonogreenz** [comment]
@Joe-houghton so I'm not going to rename the repo at this stage, but I have put this up on pypi now - so you can install it through pip. `pip install py-pushover-open-client` and then you can just do `from pushover_open_client import Client` instead of including it as a git submodule 👍 

If you have any troubles or concerns let me know.

**Comment by Joe-houghton** [comment]
Hi @aeirsoul

That's a great solution and I will update my repository to reflect this.

Joe
